#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GenerateBuildingLightUV

#include "Basic.hpp"

#include "BP_GenerateBuildingLightUV_classes.hpp"
#include "BP_GenerateBuildingLightUV_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_GenerateBuildingLightUV.BP_GenerateBuildingLightUV_C.ExecuteUbergraph_BP_GenerateBuildingLightUV
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GenerateBuildingLightUV_C::ExecuteUbergraph_BP_GenerateBuildingLightUV(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GenerateBuildingLightUV_C", "ExecuteUbergraph_BP_GenerateBuildingLightUV");

	Params::BP_GenerateBuildingLightUV_C_ExecuteUbergraph_BP_GenerateBuildingLightUV Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GenerateBuildingLightUV.BP_GenerateBuildingLightUV_C.Run
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_GenerateBuildingLightUV_C::Run()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GenerateBuildingLightUV_C", "Run");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GenerateBuildingLightUV.SKEL_BP_GenerateBuildingLightUV_C.Run
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ASKEL_BP_GenerateBuildingLightUV_C::Run()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_GenerateBuildingLightUV_C", "Run");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GenerateBuildingLightUV.SKEL_BP_GenerateBuildingLightUV_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_BP_GenerateBuildingLightUV_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_GenerateBuildingLightUV_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
