#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LoadoutContainer

#include "Basic.hpp"

#include "BP_LoadoutContainer_classes.hpp"
#include "BP_LoadoutContainer_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_LoadoutContainer.BP_LoadoutContainer_C.UpdateAnimation
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   InAnimRatio_UpdateAnimation                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LoadoutContainer_C::UpdateAnimation(float InAnimRatio_UpdateAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LoadoutContainer_C", "UpdateAnimation");

	Params::BP_LoadoutContainer_C_UpdateAnimation Parms{};

	Parms.InAnimRatio_UpdateAnimation = InAnimRatio_UpdateAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LoadoutContainer.BP_LoadoutContainer_C.ExecuteUbergraph_BP_LoadoutContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LoadoutContainer_C::ExecuteUbergraph_BP_LoadoutContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LoadoutContainer_C", "ExecuteUbergraph_BP_LoadoutContainer");

	Params::BP_LoadoutContainer_C_ExecuteUbergraph_BP_LoadoutContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LoadoutContainer.SKEL_BP_LoadoutContainer_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_BP_LoadoutContainer_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_LoadoutContainer_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LoadoutContainer.SKEL_BP_LoadoutContainer_C.UpdateAnimation
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   InAnimRatio_UpdateAnimation                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASKEL_BP_LoadoutContainer_C::UpdateAnimation(float InAnimRatio_UpdateAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_LoadoutContainer_C", "UpdateAnimation");

	Params::SKEL_BP_LoadoutContainer_C_UpdateAnimation Parms{};

	Parms.InAnimRatio_UpdateAnimation = InAnimRatio_UpdateAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
