#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MenuPlayerController

#include "Basic.hpp"

#include "BP_MenuPlayerController_classes.hpp"


SDK_NAMESPACE_START

// Function BP_MenuPlayerController.SKEL_BP_MenuPlayerController_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_BP_MenuPlayerController_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_MenuPlayerController_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
