#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicsVolume_Water

#include "Basic.hpp"

#include "BP_PhysicsVolume_Water_classes.hpp"
#include "BP_PhysicsVolume_Water_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PhysicsVolume_Water.SKEL_BP_PhysicsVolume_Water_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASKEL_BP_PhysicsVolume_Water_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_PhysicsVolume_Water_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PhysicsVolume_Water.SKEL_BP_PhysicsVolume_Water_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASKEL_BP_PhysicsVolume_Water_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_PhysicsVolume_Water_C", "ReceiveActorBeginOverlap");

	Params::SKEL_BP_PhysicsVolume_Water_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PhysicsVolume_Water.SKEL_BP_PhysicsVolume_Water_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASKEL_BP_PhysicsVolume_Water_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_PhysicsVolume_Water_C", "ReceiveTick");

	Params::SKEL_BP_PhysicsVolume_Water_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PhysicsVolume_Water.SKEL_BP_PhysicsVolume_Water_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_BP_PhysicsVolume_Water_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_PhysicsVolume_Water_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
