#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Suppressor

#include "Basic.hpp"

#include "BP_Suppressor_classes.hpp"
#include "BP_Suppressor_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Suppressor.SKEL_BP_Suppressor_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_BP_Suppressor_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_Suppressor_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Suppressor.SKEL_BP_Suppressor_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds_ReceiveTick                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASKEL_BP_Suppressor_C::ReceiveTick(float DeltaSeconds_ReceiveTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_Suppressor_C", "ReceiveTick");

	Params::SKEL_BP_Suppressor_C_ReceiveTick Parms{};

	Parms.DeltaSeconds_ReceiveTick = DeltaSeconds_ReceiveTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Suppressor.SKEL_BP_Suppressor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASKEL_BP_Suppressor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_Suppressor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
