#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VehicleAssembler

#include "Basic.hpp"

#include "BP_VehicleAssembler_classes.hpp"
#include "BP_VehicleAssembler_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_VehicleAssembler.BP_VehicleAssembler_C.ExecuteUbergraph_BP_VehicleAssembler
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VehicleAssembler_C::ExecuteUbergraph_BP_VehicleAssembler(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VehicleAssembler_C", "ExecuteUbergraph_BP_VehicleAssembler");

	Params::BP_VehicleAssembler_C_ExecuteUbergraph_BP_VehicleAssembler Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VehicleAssembler.BP_VehicleAssembler_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_VehicleAssembler_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VehicleAssembler_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VehicleAssembler.BP_VehicleAssembler_C.InpActEvt_PageUp_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_VehicleAssembler_C::InpActEvt_PageUp_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VehicleAssembler_C", "InpActEvt_PageUp_K2Node_InputKeyEvent_0");

	Params::BP_VehicleAssembler_C_InpActEvt_PageUp_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VehicleAssembler.BP_VehicleAssembler_C.ReceiveTick
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VehicleAssembler_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VehicleAssembler_C", "ReceiveTick");

	Params::BP_VehicleAssembler_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VehicleAssembler.BP_VehicleAssembler_C.InitObjects
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_VehicleAssembler_C::InitObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VehicleAssembler_C", "InitObjects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VehicleAssembler.SKEL_BP_VehicleAssembler_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASKEL_BP_VehicleAssembler_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_VehicleAssembler_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VehicleAssembler.SKEL_BP_VehicleAssembler_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_BP_VehicleAssembler_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_VehicleAssembler_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VehicleAssembler.SKEL_BP_VehicleAssembler_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASKEL_BP_VehicleAssembler_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_VehicleAssembler_C", "ReceiveTick");

	Params::SKEL_BP_VehicleAssembler_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VehicleAssembler.SKEL_BP_VehicleAssembler_C.InitObjects
// (Public, BlueprintCallable, BlueprintEvent)

void ASKEL_BP_VehicleAssembler_C::InitObjects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_BP_VehicleAssembler_C", "InitObjects");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
