#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_BP_Interface

#include "Basic.hpp"

#include "Tutorial_BP_Interface_classes.hpp"


SDK_NAMESPACE_START

// Function Tutorial_BP_Interface.SKEL_Tutorial_BP_Interface_C.TutorialSampleFunction
// (Public, BlueprintCallable, BlueprintEvent)

void ISKEL_Tutorial_BP_Interface_C::TutorialSampleFunction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("SKEL_Tutorial_BP_Interface_C", "TutorialSampleFunction");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function Tutorial_BP_Interface.Tutorial_BP_Interface_C.TutorialSampleFunction
// (Public, BlueprintCallable, BlueprintEvent)

void ITutorial_BP_Interface_C::TutorialSampleFunction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("Tutorial_BP_Interface_C", "TutorialSampleFunction");

	AsUObject()->ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
