#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_BP_Class

#include "Basic.hpp"

#include "Tutorial_BP_Class_classes.hpp"
#include "Tutorial_BP_Class_parameters.hpp"


SDK_NAMESPACE_START

// Function Tutorial_BP_Class.SKEL_Tutorial_BP_Class_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASKEL_Tutorial_BP_Class_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_Tutorial_BP_Class_C", "ReceiveTick");

	Params::SKEL_Tutorial_BP_Class_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tutorial_BP_Class.SKEL_Tutorial_BP_Class_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASKEL_Tutorial_BP_Class_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_Tutorial_BP_Class_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tutorial_BP_Class.SKEL_Tutorial_BP_Class_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_Tutorial_BP_Class_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_Tutorial_BP_Class_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tutorial_BP_Class.Tutorial_BP_Class_C.ExecuteUbergraph_Tutorial_BP_Class
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATutorial_BP_Class_C::ExecuteUbergraph_Tutorial_BP_Class(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_BP_Class_C", "ExecuteUbergraph_Tutorial_BP_Class");

	Params::Tutorial_BP_Class_C_ExecuteUbergraph_Tutorial_BP_Class Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tutorial_BP_Class.Tutorial_BP_Class_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATutorial_BP_Class_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_BP_Class_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Tutorial_BP_Class.Tutorial_BP_Class_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATutorial_BP_Class_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_BP_Class_C", "ReceiveTick");

	Params::Tutorial_BP_Class_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Tutorial_BP_Class.Tutorial_BP_Class_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ATutorial_BP_Class_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Tutorial_BP_Class_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
