#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterBody_Niagara_ShoreFoam

#include "Basic.hpp"

#include "WaterBody_Niagara_ShoreFoam_classes.hpp"
#include "WaterBody_Niagara_ShoreFoam_parameters.hpp"


SDK_NAMESPACE_START

// Function WaterBody_Niagara_ShoreFoam.WaterBody_Niagara_ShoreFoam_C.ExecuteUbergraph_WaterBody_Niagara_ShoreFoam
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWaterBody_Niagara_ShoreFoam_C::ExecuteUbergraph_WaterBody_Niagara_ShoreFoam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterBody_Niagara_ShoreFoam_C", "ExecuteUbergraph_WaterBody_Niagara_ShoreFoam");

	Params::WaterBody_Niagara_ShoreFoam_C_ExecuteUbergraph_WaterBody_Niagara_ShoreFoam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WaterBody_Niagara_ShoreFoam.WaterBody_Niagara_ShoreFoam_C.Copy Grid
// (BlueprintCallable, BlueprintEvent)

void AWaterBody_Niagara_ShoreFoam_C::Copy_Grid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterBody_Niagara_ShoreFoam_C", "Copy Grid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterBody_Niagara_ShoreFoam.WaterBody_Niagara_ShoreFoam_C.Draw
// (BlueprintCallable, BlueprintEvent)

void AWaterBody_Niagara_ShoreFoam_C::Draw()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterBody_Niagara_ShoreFoam_C", "Draw");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterBody_Niagara_ShoreFoam.WaterBody_Niagara_ShoreFoam_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AWaterBody_Niagara_ShoreFoam_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterBody_Niagara_ShoreFoam_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterBody_Niagara_ShoreFoam.SKEL_WaterBody_Niagara_ShoreFoam_C.Draw
// (BlueprintCallable, BlueprintEvent)

void ASKEL_WaterBody_Niagara_ShoreFoam_C::Draw()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WaterBody_Niagara_ShoreFoam_C", "Draw");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterBody_Niagara_ShoreFoam.SKEL_WaterBody_Niagara_ShoreFoam_C.Copy Grid
// (BlueprintCallable, BlueprintEvent)

void ASKEL_WaterBody_Niagara_ShoreFoam_C::Copy_Grid()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WaterBody_Niagara_ShoreFoam_C", "Copy Grid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterBody_Niagara_ShoreFoam.SKEL_WaterBody_Niagara_ShoreFoam_C.UserConstructionScript
// (Event, Public, BlueprintEvent)

void ASKEL_WaterBody_Niagara_ShoreFoam_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WaterBody_Niagara_ShoreFoam_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
