#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DashboardBorder

#include "Basic.hpp"

#include "WBP_DashboardBorder_classes.hpp"
#include "WBP_DashboardBorder_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_DashboardBorder.WBP_DashboardBorder_C.ExecuteUbergraph_WBP_DashboardBorder
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DashboardBorder_C::ExecuteUbergraph_WBP_DashboardBorder(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DashboardBorder_C", "ExecuteUbergraph_WBP_DashboardBorder");

	Params::WBP_DashboardBorder_C_ExecuteUbergraph_WBP_DashboardBorder Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DashboardBorder.WBP_DashboardBorder_C.InitBorder
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// EHorizontalAlignment                    InHorizontalAlignment                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInIsTitle                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_DashboardBorder_C::InitBorder(const class FText& InText, EHorizontalAlignment InHorizontalAlignment, bool bInIsTitle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DashboardBorder_C", "InitBorder");

	Params::WBP_DashboardBorder_C_InitBorder Parms{};

	Parms.InText = std::move(InText);
	Parms.InHorizontalAlignment = InHorizontalAlignment;
	Parms.bInIsTitle = bInIsTitle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DashboardBorder.SKEL_WBP_DashboardBorder_C.InitBorder
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// EHorizontalAlignment                    InHorizontalAlignment                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInIsTitle                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USKEL_WBP_DashboardBorder_C::InitBorder(const class FText& InText, EHorizontalAlignment InHorizontalAlignment, bool bInIsTitle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_DashboardBorder_C", "InitBorder");

	Params::SKEL_WBP_DashboardBorder_C_InitBorder Parms{};

	Parms.InText = std::move(InText);
	Parms.InHorizontalAlignment = InHorizontalAlignment;
	Parms.bInIsTitle = bInIsTitle;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
