#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputKey

#include "Basic.hpp"

#include "WBP_InputKey_classes.hpp"
#include "WBP_InputKey_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_InputKey.WBP_InputKey_C.ExecuteUbergraph_WBP_InputKey
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InputKey_C::ExecuteUbergraph_WBP_InputKey(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputKey_C", "ExecuteUbergraph_WBP_InputKey");

	Params::WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputKey.WBP_InputKey_C.UpdateKey
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FKeyDisplayTableRow&       DisplayInfo                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const bool                              bIsGamepadKey                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_InputKey_C::UpdateKey(const struct FKeyDisplayTableRow& DisplayInfo, const bool bIsGamepadKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputKey_C", "UpdateKey");

	Params::WBP_InputKey_C_UpdateKey Parms{};

	Parms.DisplayInfo = std::move(DisplayInfo);
	Parms.bIsGamepadKey = bIsGamepadKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputKey.SKEL_WBP_InputKey_C.UpdateKey
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FKeyDisplayTableRow&       DisplayInfo                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// const bool                              bIsGamepadKey                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USKEL_WBP_InputKey_C::UpdateKey(const struct FKeyDisplayTableRow& DisplayInfo, const bool bIsGamepadKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_InputKey_C", "UpdateKey");

	Params::SKEL_WBP_InputKey_C_UpdateKey Parms{};

	Parms.DisplayInfo = std::move(DisplayInfo);
	Parms.bIsGamepadKey = bIsGamepadKey;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
