#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCMetaDataPopup

#include "Basic.hpp"

#include "WBP_UGCMetaDataPopup_classes.hpp"
#include "WBP_UGCMetaDataPopup_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UGCMetaDataPopup.WBP_UGCMetaDataPopup_C.ExecuteUbergraph_WBP_UGCMetaDataPopup
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UGCMetaDataPopup_C::ExecuteUbergraph_WBP_UGCMetaDataPopup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UGCMetaDataPopup_C", "ExecuteUbergraph_WBP_UGCMetaDataPopup");

	Params::WBP_UGCMetaDataPopup_C_ExecuteUbergraph_WBP_UGCMetaDataPopup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UGCMetaDataPopup.WBP_UGCMetaDataPopup_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UGCMetaDataPopup_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UGCMetaDataPopup_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UGCMetaDataPopup.WBP_UGCMetaDataPopup_C.GetPopupTitle
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_UGCMetaDataPopup_C::GetPopupTitle() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UGCMetaDataPopup_C", "GetPopupTitle");

	Params::WBP_UGCMetaDataPopup_C_GetPopupTitle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UGCMetaDataPopup.SKEL_WBP_UGCMetaDataPopup_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USKEL_WBP_UGCMetaDataPopup_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_UGCMetaDataPopup_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UGCMetaDataPopup.SKEL_WBP_UGCMetaDataPopup_C.GetPopupTitle
// (Event, Public, HasOutParams, BlueprintEvent, Const)
// Parameters:
// class FText                             ReturnValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

class FText USKEL_WBP_UGCMetaDataPopup_C::GetPopupTitle() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_UGCMetaDataPopup_C", "GetPopupTitle");

	Params::SKEL_WBP_UGCMetaDataPopup_C_GetPopupTitle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
