#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuNews

#include "Basic.hpp"

#include "WBP_MenuNews_classes.hpp"
#include "WBP_MenuNews_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_MenuNews.WBP_MenuNews_C.ExecuteUbergraph_WBP_MenuNews
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MenuNews_C::ExecuteUbergraph_WBP_MenuNews(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "ExecuteUbergraph_WBP_MenuNews");

	Params::WBP_MenuNews_C_ExecuteUbergraph_WBP_MenuNews Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuNews.WBP_MenuNews_C.BndEvt__WBP_MenuNews_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_MenuNews_C::BndEvt__WBP_MenuNews_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "BndEvt__WBP_MenuNews_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.WBP_MenuNews_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MenuNews_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.WBP_MenuNews_C.OnSuccess_525CB4C942788D6D9EDF80BF367842CA
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBrLatestNewsDetails&      News                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FString&                    ErrorMessage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   HttpStatusCode                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MenuNews_C::OnSuccess_525CB4C942788D6D9EDF80BF367842CA(const struct FBrLatestNewsDetails& News, const class FString& ErrorMessage, int32 HttpStatusCode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "OnSuccess_525CB4C942788D6D9EDF80BF367842CA");

	Params::WBP_MenuNews_C_OnSuccess_525CB4C942788D6D9EDF80BF367842CA Parms{};

	Parms.News = std::move(News);
	Parms.ErrorMessage = std::move(ErrorMessage);
	Parms.HttpStatusCode = HttpStatusCode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuNews.WBP_MenuNews_C.OnFailure_525CB4C942788D6D9EDF80BF367842CA
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBrLatestNewsDetails&      News                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FString&                    ErrorMessage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   HttpStatusCode                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MenuNews_C::OnFailure_525CB4C942788D6D9EDF80BF367842CA(const struct FBrLatestNewsDetails& News, const class FString& ErrorMessage, int32 HttpStatusCode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "OnFailure_525CB4C942788D6D9EDF80BF367842CA");

	Params::WBP_MenuNews_C_OnFailure_525CB4C942788D6D9EDF80BF367842CA Parms{};

	Parms.News = std::move(News);
	Parms.ErrorMessage = std::move(ErrorMessage);
	Parms.HttpStatusCode = HttpStatusCode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuNews.WBP_MenuNews_C.OpenNewsArticle
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_MenuNews_C::OpenNewsArticle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "OpenNewsArticle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.WBP_MenuNews_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MenuNews_C::OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "OnMouseButtonUp");

	Params::WBP_MenuNews_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MenuNews.WBP_MenuNews_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MenuNews_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "OnMouseButtonDown");

	Params::WBP_MenuNews_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MenuNews.WBP_MenuNews_C.UpdatePreviewImage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_MenuNews_C::UpdatePreviewImage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuNews_C", "UpdatePreviewImage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.SKEL_WBP_MenuNews_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USKEL_WBP_MenuNews_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_MenuNews_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.SKEL_WBP_MenuNews_C.BndEvt__WBP_MenuNews_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (Public)

void USKEL_WBP_MenuNews_C::BndEvt__WBP_MenuNews_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_MenuNews_C", "BndEvt__WBP_MenuNews_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.SKEL_WBP_MenuNews_C.OpenNewsArticle
// (Public, BlueprintCallable, BlueprintEvent)

void USKEL_WBP_MenuNews_C::OpenNewsArticle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_MenuNews_C", "OpenNewsArticle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuNews.SKEL_WBP_MenuNews_C.OnMouseButtonUp
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// struct FEventReply                      ReturnValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

struct FEventReply USKEL_WBP_MenuNews_C::OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_MenuNews_C", "OnMouseButtonUp");

	Params::SKEL_WBP_MenuNews_C_OnMouseButtonUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MenuNews.SKEL_WBP_MenuNews_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// struct FEventReply                      ReturnValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

struct FEventReply USKEL_WBP_MenuNews_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_MenuNews_C", "OnMouseButtonDown");

	Params::SKEL_WBP_MenuNews_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MenuNews.SKEL_WBP_MenuNews_C.UpdatePreviewImage
// (Public, BlueprintCallable, BlueprintEvent)

void USKEL_WBP_MenuNews_C::UpdatePreviewImage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_MenuNews_C", "UpdatePreviewImage");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
