#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TeamBaseIcon

#include "Basic.hpp"

#include "WBP_TeamBaseIcon_classes.hpp"
#include "WBP_TeamBaseIcon_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_TeamBaseIcon.WBP_TeamBaseIcon_C.GetIconDisplayName
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_TeamBaseIcon_C::GetIconDisplayName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TeamBaseIcon_C", "GetIconDisplayName");

	Params::WBP_TeamBaseIcon_C_GetIconDisplayName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_TeamBaseIcon.SKEL_WBP_TeamBaseIcon_C.GetIconDisplayName
// (Event, Public, HasOutParams, BlueprintEvent, Const)
// Parameters:
// class FText                             ReturnValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

class FText USKEL_WBP_TeamBaseIcon_C::GetIconDisplayName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SKEL_WBP_TeamBaseIcon_C", "GetIconDisplayName");

	Params::SKEL_WBP_TeamBaseIcon_C_GetIconDisplayName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
