#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIGraph

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct AIGraph.AISchemaAction_NewSubNode
// 0x0010 (0x0110 - 0x0100)
struct FAISchemaAction_NewSubNode final : public FEdGraphSchemaAction
{
public:
	class UAIGraphNode*                           NodeTemplate;                                      // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAIGraphNode*                           ParentNode;                                        // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAISchemaAction_NewSubNode;

// ScriptStruct AIGraph.AISchemaAction_NewNode
// 0x0008 (0x0108 - 0x0100)
struct FAISchemaAction_NewNode final : public FEdGraphSchemaAction
{
public:
	class UAIGraphNode*                           NodeTemplate;                                      // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FAISchemaAction_NewNode;

// ScriptStruct AIGraph.AISchemaAction_AddComment
// 0x0000 (0x0100 - 0x0100)
struct FAISchemaAction_AddComment final : public FEdGraphSchemaAction
{
};
DUMPER7_ASSERTS_FAISchemaAction_AddComment;

// ScriptStruct AIGraph.GraphNodeClassData
// 0x0068 (0x0068 - 0x0000)
struct FGraphNodeClassData final
{
public:
	uint8                                         Pad_0[0x10];                                       // 0x0000(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AssetName;                                         // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 GeneratedClassPackage;                             // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 ClassName;                                         // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FText                                   Category;                                          // 0x0040(0x0018)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_58[0x10];                                      // 0x0058(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FGraphNodeClassData;

SDK_NAMESPACE_END
