#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimationModifiers

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function AnimationModifiers.AnimationBlueprintLibrary.AddAnimationNotifyEvent
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_AddAnimationNotifyEvent final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimNotify>                NotifyClass;                                       // 0x0018(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimNotify*                      ReturnValue;                                       // 0x0020(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddAnimationNotifyEvent;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddAnimationNotifyEventObject
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_AddAnimationNotifyEventObject final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UAnimNotify*                      Notify;                                            // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddAnimationNotifyEventObject;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddAnimationNotifyStateEvent
// 0x0030 (0x0030 - 0x0000)
struct AnimationBlueprintLibrary_AddAnimationNotifyStateEvent final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Duration;                                          // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UAnimNotifyState>           NotifyStateClass;                                  // 0x0020(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimNotifyState*                 ReturnValue;                                       // 0x0028(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddAnimationNotifyStateEvent;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddAnimationNotifyStateEventObject
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_AddAnimationNotifyStateEventObject final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Duration;                                          // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimNotifyState*                 NotifyState;                                       // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddAnimationNotifyStateEventObject;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddAnimationNotifyTrack
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_AddAnimationNotifyTrack final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           TrackColor;                                        // 0x0014(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddAnimationNotifyTrack;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddAnimationSyncMarker
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_AddAnimationSyncMarker final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   MarkerName;                                        // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddAnimationSyncMarker;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddCurve
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_AddCurve final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERawCurveTrackTypes                           CurveType;                                         // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bMetaDataCurve;                                    // 0x0015(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddCurve;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddFloatCurveKey
// 0x0020 (0x0020 - 0x0000)
struct AnimationBlueprintLibrary_AddFloatCurveKey final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0014(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0018(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddFloatCurveKey;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddFloatCurveKeys
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_AddFloatCurveKeys final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Times;                                             // 0x0018(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	TArray<float>                                 Values;                                            // 0x0028(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddFloatCurveKeys;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddMetaData
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_AddMetaData final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimMetaData>              MetaDataClass;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimMetaData*                    MetaDataInstance;                                  // 0x0010(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddMetaData;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddMetaDataObject
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_AddMetaDataObject final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimMetaData*                    MetaDataObject;                                    // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddMetaDataObject;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddTransformationCurveKey
// 0x0050 (0x0050 - 0x0000)
struct AnimationBlueprintLibrary_AddTransformationCurveKey final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0014(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Transform;                                         // 0x0020(0x0030)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddTransformationCurveKey;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddTransformationCurveKeys
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_AddTransformationCurveKeys final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Times;                                             // 0x0018(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	TArray<struct FTransform>                     Transforms;                                        // 0x0028(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddTransformationCurveKeys;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddVectorCurveKey
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_AddVectorCurveKey final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0014(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Vector;                                            // 0x0018(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddVectorCurveKey;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddVectorCurveKeys
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_AddVectorCurveKeys final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Times;                                             // 0x0018(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        Vectors;                                           // 0x0028(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddVectorCurveKeys;

// Function AnimationModifiers.AnimationBlueprintLibrary.AddVirtualBone
// 0x0030 (0x0030 - 0x0000)
struct AnimationBlueprintLibrary_AddVirtualBone final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   SourceBoneName;                                    // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TargetBoneName;                                    // 0x0014(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   VirtualBoneName;                                   // 0x0020(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_AddVirtualBone;

// Function AnimationModifiers.AnimationBlueprintLibrary.ContainsMetaDataOfClass
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_ContainsMetaDataOfClass final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimMetaData>              MetaDataClass;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_ContainsMetaDataOfClass;

// Function AnimationModifiers.AnimationBlueprintLibrary.CopyAnimNotifiesFromSequence
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_CopyAnimNotifiesFromSequence final
{
public:
	class UAnimSequence*                          SrcAnimSequence;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAnimSequence*                          DestAnimSequence;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_CopyAnimNotifiesFromSequence;

// Function AnimationModifiers.AnimationBlueprintLibrary.DoesBoneNameExist
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_DoesBoneNameExist final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BoneName;                                          // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExists;                                           // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_DoesBoneNameExist;

// Function AnimationModifiers.AnimationBlueprintLibrary.DoesCurveExist
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_DoesCurveExist final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERawCurveTrackTypes                           CurveType;                                         // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0015(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_DoesCurveExist;

// Function AnimationModifiers.AnimationBlueprintLibrary.FinalizeBoneAnimation
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_FinalizeBoneAnimation final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_FinalizeBoneAnimation;

// Function AnimationModifiers.AnimationBlueprintLibrary.FindBonePathToRoot
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_FindBonePathToRoot final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BoneName;                                          // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           BonePath;                                          // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_FindBonePathToRoot;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAdditiveAnimationType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetAdditiveAnimationType final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAdditiveAnimationType                        AdditiveAnimationType;                             // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAdditiveAnimationType;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAdditiveBasePoseType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetAdditiveBasePoseType final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAdditiveBasePoseType                         AdditiveBasePoseType;                              // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAdditiveBasePoseType;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationCurveNames
// 0x0020 (0x0020 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationCurveNames final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERawCurveTrackTypes                           CurveType;                                         // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CurveNames;                                        // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationCurveNames;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationInterpolationType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationInterpolationType final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAnimInterpolationType                        InterpolationType;                                 // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationInterpolationType;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationNotifyEventNames
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationNotifyEventNames final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           EventNames;                                        // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationNotifyEventNames;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationNotifyEvents
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationNotifyEvents final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FAnimNotifyEvent>               NotifyEvents;                                      // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationNotifyEvents;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationNotifyEventsForTrack
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationNotifyEventsForTrack final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FAnimNotifyEvent>               Events;                                            // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationNotifyEventsForTrack;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationNotifyTrackNames
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationNotifyTrackNames final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           TrackNames;                                        // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationNotifyTrackNames;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationSyncMarkers
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationSyncMarkers final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FAnimSyncMarker>                Markers;                                           // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationSyncMarkers;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationSyncMarkersForTrack
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationSyncMarkersForTrack final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FAnimSyncMarker>                Markers;                                           // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationSyncMarkersForTrack;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimationTrackNames
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimationTrackNames final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           TrackNames;                                        // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimationTrackNames;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetAnimNotifyEventTriggerTime
// 0x00E8 (0x00E8 - 0x0000)
struct AnimationBlueprintLibrary_GetAnimNotifyEventTriggerTime final
{
public:
	struct FAnimNotifyEvent                       NotifyEvent;                                       // 0x0000(0x00E0)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x00E0(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetAnimNotifyEventTriggerTime;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetBoneCompressionSettings
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetBoneCompressionSettings final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAnimBoneCompressionSettings*           CompressionSettings;                               // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetBoneCompressionSettings;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetBonePoseForFrame
// 0x0050 (0x0050 - 0x0000)
struct AnimationBlueprintLibrary_GetBonePoseForFrame final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BoneName;                                          // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Frame;                                             // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExtractRootMotion;                                // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Pose;                                              // 0x0020(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetBonePoseForFrame;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetBonePoseForTime
// 0x0050 (0x0050 - 0x0000)
struct AnimationBlueprintLibrary_GetBonePoseForTime final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BoneName;                                          // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExtractRootMotion;                                // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Pose;                                              // 0x0020(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetBonePoseForTime;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetBonePosesForFrame
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_GetBonePosesForFrame final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           BoneNames;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         Frame;                                             // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExtractRootMotion;                                // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FTransform>                     Poses;                                             // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	const class USkeletalMesh*                    PreviewMesh;                                       // 0x0030(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetBonePosesForFrame;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetBonePosesForTime
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_GetBonePosesForTime final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           BoneNames;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bExtractRootMotion;                                // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FTransform>                     Poses;                                             // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	const class USkeletalMesh*                    PreviewMesh;                                       // 0x0030(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetBonePosesForTime;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetCurveCompressionSettings
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetCurveCompressionSettings final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAnimCurveCompressionSettings*          CompressionSettings;                               // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetCurveCompressionSettings;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetFloatKeys
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_GetFloatKeys final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Times;                                             // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<float>                                 Values;                                            // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetFloatKeys;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetFrameAtTime
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetFrameAtTime final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0008(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Frame;                                             // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetFrameAtTime;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetMetaData
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetMetaData final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UAnimMetaData*>                  MetaData;                                          // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetMetaData;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetMetaDataOfClass
// 0x0020 (0x0020 - 0x0000)
struct AnimationBlueprintLibrary_GetMetaDataOfClass final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimMetaData>              MetaDataClass;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UAnimMetaData*>                  MetaDataOfClass;                                   // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetMetaDataOfClass;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetNumFrames
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetNumFrames final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumFrames;                                         // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetNumFrames;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetRateScale
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetRateScale final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RateScale;                                         // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetRateScale;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetRawTrackData
// 0x0048 (0x0048 - 0x0000)
struct AnimationBlueprintLibrary_GetRawTrackData final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TrackName;                                         // 0x0008(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        PositionKeys;                                      // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FQuat>                          RotationKeys;                                      // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        ScalingKeys;                                       // 0x0038(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetRawTrackData;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetRawTrackPositionData
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_GetRawTrackPositionData final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TrackName;                                         // 0x0008(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        PositionData;                                      // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetRawTrackPositionData;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetRawTrackRotationData
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_GetRawTrackRotationData final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TrackName;                                         // 0x0008(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FQuat>                          RotationData;                                      // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetRawTrackRotationData;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetRawTrackScaleData
// 0x0028 (0x0028 - 0x0000)
struct AnimationBlueprintLibrary_GetRawTrackScaleData final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TrackName;                                         // 0x0008(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        ScaleData;                                         // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetRawTrackScaleData;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetRootMotionLockType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetRootMotionLockType final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERootMotionRootLock                           LockType;                                          // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetRootMotionLockType;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetSequenceLength
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetSequenceLength final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Length;                                            // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetSequenceLength;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetTimeAtFrame
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_GetTimeAtFrame final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Frame;                                             // 0x0008(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetTimeAtFrame;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetTransformationKeys
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_GetTransformationKeys final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Times;                                             // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FTransform>                     Values;                                            // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetTransformationKeys;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetUniqueMarkerNames
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_GetUniqueMarkerNames final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           MarkerNames;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetUniqueMarkerNames;

// Function AnimationModifiers.AnimationBlueprintLibrary.GetVectorKeys
// 0x0038 (0x0038 - 0x0000)
struct AnimationBlueprintLibrary_GetVectorKeys final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 Times;                                             // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        Values;                                            // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_GetVectorKeys;

// Function AnimationModifiers.AnimationBlueprintLibrary.IsRootMotionEnabled
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_IsRootMotionEnabled final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_IsRootMotionEnabled;

// Function AnimationModifiers.AnimationBlueprintLibrary.IsRootMotionLockForced
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_IsRootMotionLockForced final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_IsRootMotionLockForced;

// Function AnimationModifiers.AnimationBlueprintLibrary.IsValidAnimationSyncMarkerName
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_IsValidAnimationSyncMarkerName final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   MarkerName;                                        // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_IsValidAnimationSyncMarkerName;

// Function AnimationModifiers.AnimationBlueprintLibrary.IsValidAnimNotifyTrackName
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_IsValidAnimNotifyTrackName final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_IsValidAnimNotifyTrackName;

// Function AnimationModifiers.AnimationBlueprintLibrary.IsValidRawAnimationTrackName
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_IsValidRawAnimationTrackName final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   TrackName;                                         // 0x0008(0x000C)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_IsValidRawAnimationTrackName;

// Function AnimationModifiers.AnimationBlueprintLibrary.IsValidTime
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_IsValidTime final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0008(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsValid;                                           // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_IsValidTime;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAllAnimationNotifyTracks
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAllAnimationNotifyTracks final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAllAnimationNotifyTracks;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAllAnimationSyncMarkers
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAllAnimationSyncMarkers final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAllAnimationSyncMarkers;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAllBoneAnimation
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAllBoneAnimation final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAllBoneAnimation;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAllCurveData
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAllCurveData final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAllCurveData;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAllMetaData
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAllMetaData final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAllMetaData;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAllVirtualBones
// 0x0008 (0x0008 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAllVirtualBones final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAllVirtualBones;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAnimationNotifyEventsByName
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAnimationNotifyEventsByName final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyName;                                        // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAnimationNotifyEventsByName;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAnimationNotifyEventsByTrack
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAnimationNotifyEventsByTrack final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAnimationNotifyEventsByTrack;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAnimationNotifyTrack
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAnimationNotifyTrack final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAnimationNotifyTrack;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAnimationSyncMarkersByName
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAnimationSyncMarkersByName final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   MarkerName;                                        // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAnimationSyncMarkersByName;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveAnimationSyncMarkersByTrack
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveAnimationSyncMarkersByTrack final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   NotifyTrackName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0014(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveAnimationSyncMarkersByTrack;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveBoneAnimation
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveBoneAnimation final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   BoneName;                                          // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeChildren;                                  // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFinalize;                                         // 0x0015(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveBoneAnimation;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveCurve
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveCurve final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CurveName;                                         // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bRemoveNameFromSkeleton;                           // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveCurve;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveMetaData
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_RemoveMetaData final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class UAnimMetaData*                    MetaDataObject;                                    // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveMetaData;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveMetaDataOfClass
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_RemoveMetaDataOfClass final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimMetaData>              MetaDataClass;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveMetaDataOfClass;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveVirtualBone
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveVirtualBone final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   VirtualBoneName;                                   // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveVirtualBone;

// Function AnimationModifiers.AnimationBlueprintLibrary.RemoveVirtualBones
// 0x0018 (0x0018 - 0x0000)
struct AnimationBlueprintLibrary_RemoveVirtualBones final
{
public:
	const class UAnimSequence*                    AnimationSequence;                                 // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           VirtualBoneNames;                                  // 0x0008(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_RemoveVirtualBones;

// Function AnimationModifiers.AnimationBlueprintLibrary.ReplaceAnimNotifies
// 0x0030 (0x0030 - 0x0000)
struct AnimationBlueprintLibrary_ReplaceAnimNotifies final
{
public:
	class UAnimSequenceBase*                      AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimNotify>                OldNotifyClass;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimNotify>                NewNotifyClass;                                    // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(const class UAnimNotify* OldNotify, const class UAnimNotify* NewNotify)> OnNotifyReplaced; // 0x0018(0x0014)(Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_ReplaceAnimNotifies;

// Function AnimationModifiers.AnimationBlueprintLibrary.ReplaceAnimNotifyStates
// 0x0030 (0x0030 - 0x0000)
struct AnimationBlueprintLibrary_ReplaceAnimNotifyStates final
{
public:
	class UAnimSequenceBase*                      AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimNotifyState>           OldNotifyClass;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UAnimNotifyState>           NewNotifyClass;                                    // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(const class UAnimNotifyState* OldNotifyState, const class UAnimNotifyState* NewNotifyState)> OnNotifyStateReplaced; // 0x0018(0x0014)(Parm, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_ReplaceAnimNotifyStates;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetAdditiveAnimationType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetAdditiveAnimationType final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAdditiveAnimationType                        AdditiveAnimationType;                             // 0x0008(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetAdditiveAnimationType;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetAdditiveBasePoseType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetAdditiveBasePoseType final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAdditiveBasePoseType                         AdditiveBasePoseType;                              // 0x0008(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetAdditiveBasePoseType;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetAnimationInterpolationType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetAnimationInterpolationType final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAnimInterpolationType                        InterpolationType;                                 // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetAnimationInterpolationType;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetBoneCompressionSettings
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetBoneCompressionSettings final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAnimBoneCompressionSettings*           CompressionSettings;                               // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetBoneCompressionSettings;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetCurveCompressionSettings
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetCurveCompressionSettings final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAnimCurveCompressionSettings*          CompressionSettings;                               // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetCurveCompressionSettings;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetIsRootMotionLockForced
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetIsRootMotionLockForced final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForced;                                           // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetIsRootMotionLockForced;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetRateScale
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetRateScale final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RateScale;                                         // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetRateScale;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetRootMotionEnabled
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetRootMotionEnabled final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnabled;                                          // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetRootMotionEnabled;

// Function AnimationModifiers.AnimationBlueprintLibrary.SetRootMotionLockType
// 0x0010 (0x0010 - 0x0000)
struct AnimationBlueprintLibrary_SetRootMotionLockType final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ERootMotionRootLock                           RootMotionLockType;                                // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AnimationBlueprintLibrary_SetRootMotionLockType;

// Function AnimationModifiers.AnimationModifier.OnApply
// 0x0008 (0x0008 - 0x0000)
struct AnimationModifier_OnApply final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationModifier_OnApply;

// Function AnimationModifiers.AnimationModifier.OnRevert
// 0x0008 (0x0008 - 0x0000)
struct AnimationModifier_OnRevert final
{
public:
	class UAnimSequence*                          AnimationSequence;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AnimationModifier_OnRevert;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
