#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutomationUtilsEditor

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class AutomationUtilsEditor.ScreenshotComparisonCommandlet
// 0x0000 (0x0088 - 0x0088)
class UScreenshotComparisonCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ScreenshotComparisonCommandlet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ScreenshotComparisonCommandlet")
	}
	static class UScreenshotComparisonCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScreenshotComparisonCommandlet>();
	}
};
DUMPER7_ASSERTS_UScreenshotComparisonCommandlet;

SDK_NAMESPACE_END
