#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BlueprintNativeCodeGen

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct BlueprintNativeCodeGen.ConvertedAssetRecord
// 0x0038 (0x0038 - 0x0000)
struct FConvertedAssetRecord final
{
public:
	class UClass*                                 AssetType;                                         // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 TargetObjPath;                                     // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 GeneratedHeaderPath;                               // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 GeneratedCppPath;                                  // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FConvertedAssetRecord;

// ScriptStruct BlueprintNativeCodeGen.UnconvertedDependencyRecord
// 0x0010 (0x0010 - 0x0000)
struct FUnconvertedDependencyRecord final
{
public:
	class FString                                 GeneratedWrapperPath;                              // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FUnconvertedDependencyRecord;

// ScriptStruct BlueprintNativeCodeGen.BlueprintNativeCodeGenManifest
// 0x0158 (0x0158 - 0x0000)
struct FBlueprintNativeCodeGenManifest final
{
public:
	int32                                         ManifestChunkId;                                   // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PluginName;                                        // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 OutputDir;                                         // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class UPackage*>                       ModuleDependencies;                                // 0x0028(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TMap<class FName, struct FConvertedAssetRecord> ConvertedAssets;                                 // 0x0038(0x0050)(NativeAccessSpecifierPrivate)
	TMap<class FName, struct FUnconvertedDependencyRecord> UnconvertedDependencies;                  // 0x0088(0x0050)(NativeAccessSpecifierPrivate)
	struct FCompilerNativizationOptions           NativizationOptions;                               // 0x00D8(0x0080)(NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FBlueprintNativeCodeGenManifest;

SDK_NAMESPACE_END
