#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Billboard

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Billboard.BP_Billboard_C
// 0x0000 (0x0358 - 0x0358)
class ABP_Billboard_C final : public ABillboard
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Billboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Billboard_C")
	}
	static class ABP_Billboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Billboard_C>();
	}
};
DUMPER7_ASSERTS_ABP_Billboard_C;

// BlueprintGeneratedClass BP_Billboard.SKEL_BP_Billboard_C
// 0x0010 (0x0368 - 0x0358)
class ASKEL_BP_Billboard_C final : public ABillboard
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0358(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_Billboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_Billboard_C")
	}
	static class ASKEL_BP_Billboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASKEL_BP_Billboard_C>();
	}
};
DUMPER7_ASSERTS_ASKEL_BP_Billboard_C;

SDK_NAMESPACE_END
