#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CornerBrick_2x2x1

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CornerBrick_2x2x1.BP_CornerBrick_2x2x1_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_CornerBrick_2x2x1_C final : public UBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CornerBrick_2x2x1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CornerBrick_2x2x1_C")
	}
	static class UBP_CornerBrick_2x2x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CornerBrick_2x2x1_C>();
	}
};
DUMPER7_ASSERTS_UBP_CornerBrick_2x2x1_C;

// BlueprintGeneratedClass BP_CornerBrick_2x2x1.SKEL_BP_CornerBrick_2x2x1_C
// 0x0010 (0x01B0 - 0x01A0)
class USKEL_BP_CornerBrick_2x2x1_C final : public UBrickStaticInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01A0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_CornerBrick_2x2x1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_CornerBrick_2x2x1_C")
	}
	static class USKEL_BP_CornerBrick_2x2x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_BP_CornerBrick_2x2x1_C>();
	}
};
DUMPER7_ASSERTS_USKEL_BP_CornerBrick_2x2x1_C;

SDK_NAMESPACE_END
