#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Coupling_4x1x2s_Bottom

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Coupling_4x1x2s_Bottom.BP_Coupling_4x1x2s_Bottom_C
// 0x0000 (0x01B0 - 0x01B0)
class UBP_Coupling_4x1x2s_Bottom_C final : public UCouplingBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Coupling_4x1x2s_Bottom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Coupling_4x1x2s_Bottom_C")
	}
	static class UBP_Coupling_4x1x2s_Bottom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Coupling_4x1x2s_Bottom_C>();
	}
};
DUMPER7_ASSERTS_UBP_Coupling_4x1x2s_Bottom_C;

// BlueprintGeneratedClass BP_Coupling_4x1x2s_Bottom.SKEL_BP_Coupling_4x1x2s_Bottom_C
// 0x0010 (0x01C0 - 0x01B0)
class USKEL_BP_Coupling_4x1x2s_Bottom_C final : public UCouplingBrickStaticInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01B0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_Coupling_4x1x2s_Bottom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_Coupling_4x1x2s_Bottom_C")
	}
	static class USKEL_BP_Coupling_4x1x2s_Bottom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_BP_Coupling_4x1x2s_Bottom_C>();
	}
};
DUMPER7_ASSERTS_USKEL_BP_Coupling_4x1x2s_Bottom_C;

SDK_NAMESPACE_END
