#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GunshotSoundTester

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GunshotSoundTester.BP_GunshotSoundTester_C
// 0x0020 (0x0318 - 0x02F8)
class ABP_GunshotSoundTester_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F8(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        Audio;                                             // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         ShotsFired;                                        // 0x0310(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_GunshotSoundTester(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GunshotSoundTester_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GunshotSoundTester_C")
	}
	static class ABP_GunshotSoundTester_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GunshotSoundTester_C>();
	}
};
DUMPER7_ASSERTS_ABP_GunshotSoundTester_C;

// BlueprintGeneratedClass BP_GunshotSoundTester.SKEL_BP_GunshotSoundTester_C
// 0x0020 (0x0318 - 0x02F8)
class ASKEL_BP_GunshotSoundTester_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F8(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        Audio;                                             // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         ShotsFired;                                        // 0x0310(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_GunshotSoundTester_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_GunshotSoundTester_C")
	}
	static class ASKEL_BP_GunshotSoundTester_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASKEL_BP_GunshotSoundTester_C>();
	}
};
DUMPER7_ASSERTS_ASKEL_BP_GunshotSoundTester_C;

SDK_NAMESPACE_END
