#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Launcher_4x2sx2s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Launcher_4x2sx2s.BP_Launcher_4x2sx2s_C
// 0x0000 (0x02F0 - 0x02F0)
class UBP_Launcher_4x2sx2s_C final : public ULauncherBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Launcher_4x2sx2s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Launcher_4x2sx2s_C")
	}
	static class UBP_Launcher_4x2sx2s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Launcher_4x2sx2s_C>();
	}
};
DUMPER7_ASSERTS_UBP_Launcher_4x2sx2s_C;

// BlueprintGeneratedClass BP_Launcher_4x2sx2s.SKEL_BP_Launcher_4x2sx2s_C
// 0x0010 (0x0300 - 0x02F0)
class USKEL_BP_Launcher_4x2sx2s_C final : public ULauncherBrickStaticInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_Launcher_4x2sx2s_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_Launcher_4x2sx2s_C")
	}
	static class USKEL_BP_Launcher_4x2sx2s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_BP_Launcher_4x2sx2s_C>();
	}
};
DUMPER7_ASSERTS_USKEL_BP_Launcher_4x2sx2s_C;

SDK_NAMESPACE_END
