#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpawnOverlapTest

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SpawnOverlapTest.BP_SpawnOverlapTest_C
// 0x0018 (0x0310 - 0x02F8)
class ABP_SpawnOverlapTest_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F8(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_SpawnOverlapTest(int32 EntryPoint);
	void ReceiveBeginPlay();
	class ABP_BrickVehicle_C* SpawnVehicle(float Delay, const struct FVector& Location, TArray<class FName>& Tags_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SpawnOverlapTest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SpawnOverlapTest_C")
	}
	static class ABP_SpawnOverlapTest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SpawnOverlapTest_C>();
	}
};
DUMPER7_ASSERTS_ABP_SpawnOverlapTest_C;

// BlueprintGeneratedClass BP_SpawnOverlapTest.SKEL_BP_SpawnOverlapTest_C
// 0x0018 (0x0310 - 0x02F8)
class ASKEL_BP_SpawnOverlapTest_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F8(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void UserConstructionScript();
	class ABP_BrickVehicle_C* SpawnVehicle(float Delay, const struct FVector& Location, TArray<class FName>& Tags_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_SpawnOverlapTest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_SpawnOverlapTest_C")
	}
	static class ASKEL_BP_SpawnOverlapTest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASKEL_BP_SpawnOverlapTest_C>();
	}
};
DUMPER7_ASSERTS_ASKEL_BP_SpawnOverlapTest_C;

SDK_NAMESPACE_END
