#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableCorner

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ScalableCorner.BP_ScalableCorner_C
// 0x0000 (0x01E0 - 0x01E0)
class UBP_ScalableCorner_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScalableCorner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScalableCorner_C")
	}
	static class UBP_ScalableCorner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableCorner_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScalableCorner_C;

// BlueprintGeneratedClass BP_ScalableCorner.SKEL_BP_ScalableCorner_C
// 0x0010 (0x01F0 - 0x01E0)
class USKEL_BP_ScalableCorner_C final : public UScalableBrickStaticInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01E0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_ScalableCorner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_ScalableCorner_C")
	}
	static class USKEL_BP_ScalableCorner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_BP_ScalableCorner_C>();
	}
};
DUMPER7_ASSERTS_USKEL_BP_ScalableCorner_C;

SDK_NAMESPACE_END
