#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ThrusterCylinder_02

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ThrusterCylinder_02.BP_ThrusterCylinder_02_C
// 0x0000 (0x0248 - 0x0248)
class UBP_ThrusterCylinder_02_C final : public UThrusterBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ThrusterCylinder_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ThrusterCylinder_02_C")
	}
	static class UBP_ThrusterCylinder_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ThrusterCylinder_02_C>();
	}
};
DUMPER7_ASSERTS_UBP_ThrusterCylinder_02_C;

// BlueprintGeneratedClass BP_ThrusterCylinder_02.SKEL_BP_ThrusterCylinder_02_C
// 0x0010 (0x0258 - 0x0248)
class USKEL_BP_ThrusterCylinder_02_C final : public UThrusterBrickStaticInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_ThrusterCylinder_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_ThrusterCylinder_02_C")
	}
	static class USKEL_BP_ThrusterCylinder_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_BP_ThrusterCylinder_02_C>();
	}
};
DUMPER7_ASSERTS_USKEL_BP_ThrusterCylinder_02_C;

SDK_NAMESPACE_END
