#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ThumbnailCaptureTest

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ThumbnailCaptureTest.BP_ThumbnailCaptureTest_C
// 0x0010 (0x0320 - 0x0310)
class ABP_ThumbnailCaptureTest_C final : public ASceneCapture2D
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ThumbnailCaptureTest(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ThumbnailCaptureTest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ThumbnailCaptureTest_C")
	}
	static class ABP_ThumbnailCaptureTest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ThumbnailCaptureTest_C>();
	}
};
DUMPER7_ASSERTS_ABP_ThumbnailCaptureTest_C;

// BlueprintGeneratedClass BP_ThumbnailCaptureTest.SKEL_BP_ThumbnailCaptureTest_C
// 0x0010 (0x0320 - 0x0310)
class ASKEL_BP_ThumbnailCaptureTest_C final : public ASceneCapture2D
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_ThumbnailCaptureTest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_ThumbnailCaptureTest_C")
	}
	static class ASKEL_BP_ThumbnailCaptureTest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASKEL_BP_ThumbnailCaptureTest_C>();
	}
};
DUMPER7_ASSERTS_ASKEL_BP_ThumbnailCaptureTest_C;

SDK_NAMESPACE_END
