#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wing_2x2x1s_R

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Wing_2x2x1s_R.BP_Wing_2x2x1s_R_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_Wing_2x2x1s_R_C final : public UWingBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Wing_2x2x1s_R_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Wing_2x2x1s_R_C")
	}
	static class UBP_Wing_2x2x1s_R_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Wing_2x2x1s_R_C>();
	}
};
DUMPER7_ASSERTS_UBP_Wing_2x2x1s_R_C;

// BlueprintGeneratedClass BP_Wing_2x2x1s_R.SKEL_BP_Wing_2x2x1s_R_C
// 0x0010 (0x01B0 - 0x01A0)
class USKEL_BP_Wing_2x2x1s_R_C final : public UWingBrickStaticInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01A0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_BP_Wing_2x2x1s_R_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_BP_Wing_2x2x1s_R_C")
	}
	static class USKEL_BP_Wing_2x2x1s_R_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_BP_Wing_2x2x1s_R_C>();
	}
};
DUMPER7_ASSERTS_USKEL_BP_Wing_2x2x1s_R_C;

SDK_NAMESPACE_END
