#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClothingSystemEditor

#include "Basic.hpp"

#include "ClothingSystemEditorInterface_classes.hpp"


SDK_NAMESPACE_START

// Class ClothingSystemEditor.ClothingAssetFactory
// 0x0000 (0x0030 - 0x0030)
class UClothingAssetFactory final : public UClothingAssetFactoryBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ClothingAssetFactory")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ClothingAssetFactory")
	}
	static class UClothingAssetFactory* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClothingAssetFactory>();
	}
};
DUMPER7_ASSERTS_UClothingAssetFactory;

SDK_NAMESPACE_END
