#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ContentBrowserClassDataSource

#include "Basic.hpp"


SDK_NAMESPACE_START

// ScriptStruct ContentBrowserClassDataSource.ContentBrowserCompiledClassDataFilter
// 0x00A0 (0x00A0 - 0x0000)
struct FContentBrowserCompiledClassDataFilter final
{
public:
	TSet<class UClass*>                           ValidClasses;                                      // 0x0000(0x0050)(NativeAccessSpecifierPublic)
	TSet<class FName>                             ValidFolders;                                      // 0x0050(0x0050)(NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FContentBrowserCompiledClassDataFilter;

SDK_NAMESPACE_END
