#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_RotationDefinitionApproach

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_RotationDefinitionApproach.ENiagara_RotationDefinitionApproach
// NumValues: 0x0006
enum class ENiagara_RotationDefinitionApproach : uint8
{
	NewEnumerator2                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator0                           = 2,
	NewEnumerator5                           = 3,
	NewEnumerator4                           = 4,
	ENiagara_MAX                             = 5,
};

SDK_NAMESPACE_END
