#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_WaveformCount

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_WaveformCount.ENiagara_WaveformCount
// NumValues: 0x0004
enum class ENiagara_WaveformCount : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	ENiagara_MAX                             = 3,
};

SDK_NAMESPACE_END
