#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagaraGPUDepthResponseType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagaraGPUDepthResponseType.ENiagaraGPUDepthResponseType
// NumValues: 0x0003
enum class ENiagaraGPUDepthResponseType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	ENiagaraGPUDepthResponseType_MAX         = 2,
};

SDK_NAMESPACE_END
