#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_CPUCollisionType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagara_CPUCollisionType.ENiagara_CPUCollisionType
// NumValues: 0x0003
enum class ENiagara_CPUCollisionType : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator3                           = 1,
	ENiagara_MAX                             = 2,
};

SDK_NAMESPACE_END
