#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagaraSkelSamplingModeFull

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum ENiagaraSkelSamplingModeFull.ENiagaraSkelSamplingModeFull
// NumValues: 0x0006
enum class ENiagaraSkelSamplingModeFull : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator5                           = 1,
	NewEnumerator6                           = 2,
	NewEnumerator7                           = 3,
	NewEnumerator8                           = 4,
	ENiagaraSkelSamplingModeFull_MAX         = 5,
};

SDK_NAMESPACE_END
