#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FoliageWalkThrough

#include "Basic.hpp"

#include "IntroTutorials_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass FoliageWalkThrough.FoliageWalkThrough_C
// 0x0000 (0x0160 - 0x0160)
class UFoliageWalkThrough_C final : public UEditorTutorial
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FoliageWalkThrough_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FoliageWalkThrough_C")
	}
	static class UFoliageWalkThrough_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFoliageWalkThrough_C>();
	}
};
DUMPER7_ASSERTS_UFoliageWalkThrough_C;

// BlueprintGeneratedClass FoliageWalkThrough.SKEL_FoliageWalkThrough_C
// 0x0010 (0x0170 - 0x0160)
class USKEL_FoliageWalkThrough_C final : public UEditorTutorial
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0160(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_FoliageWalkThrough_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_FoliageWalkThrough_C")
	}
	static class USKEL_FoliageWalkThrough_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_FoliageWalkThrough_C>();
	}
};
DUMPER7_ASSERTS_USKEL_FoliageWalkThrough_C;

SDK_NAMESPACE_END
