#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameProjectGeneration

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum GameProjectGeneration.ETemplateSetting
// NumValues: 0x0008
enum class ETemplateSetting : uint8
{
	Languages                                = 0,
	HardwareTarget                           = 1,
	GraphicsPreset                           = 2,
	StarterContent                           = 3,
	XR                                       = 4,
	Raytracing                               = 5,
	All                                      = 6,
	ETemplateSetting_MAX                     = 7,
};

// ScriptStruct GameProjectGeneration.LocalizedTemplateString
// 0x0020 (0x0020 - 0x0000)
struct FLocalizedTemplateString final
{
public:
	class FString                                 Language;                                          // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Text;                                              // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FLocalizedTemplateString;

// ScriptStruct GameProjectGeneration.TemplateCategoryDef
// 0x0048 (0x0048 - 0x0000)
struct FTemplateCategoryDef final
{
public:
	class FName                                   Key;                                               // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FLocalizedTemplateString>       LocalizedDisplayNames;                             // 0x0010(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FLocalizedTemplateString>       LocalizedDescriptions;                             // 0x0020(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 Icon;                                              // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsMajorCategory;                                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FTemplateCategoryDef;

// ScriptStruct GameProjectGeneration.TemplateFolderRename
// 0x0020 (0x0020 - 0x0000)
struct FTemplateFolderRename final
{
public:
	class FString                                 From;                                              // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 To;                                                // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FTemplateFolderRename;

// ScriptStruct GameProjectGeneration.TemplateReplacement
// 0x0038 (0x0038 - 0x0000)
struct FTemplateReplacement final
{
public:
	TArray<class FString>                         Extensions;                                        // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	class FString                                 From;                                              // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 To;                                                // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCaseSensitive;                                    // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FTemplateReplacement;

SDK_NAMESPACE_END
