#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HardwareTargeting

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum HardwareTargeting.EGraphicsPreset
// NumValues: 0x0004
enum class EGraphicsPreset : uint8
{
	Unspecified                              = 0,
	Maximum                                  = 1,
	Scalable                                 = 2,
	EGraphicsPreset_MAX                      = 3,
};

// Enum HardwareTargeting.EHardwareClass
// NumValues: 0x0004
enum class EHardwareClass : uint8
{
	Unspecified                              = 0,
	Desktop                                  = 1,
	Mobile                                   = 2,
	EHardwareClass_MAX                       = 3,
};

SDK_NAMESPACE_END
