#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Kismet

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// Enum Kismet.EContextTargetFlags
// NumValues: 0x0008
enum class EContextTargetFlags : uint8
{
	TARGET_Blueprint                         = 1,
	TARGET_SubComponents                     = 2,
	TARGET_NodeTarget                        = 4,
	TARGET_PinObject                         = 8,
	TARGET_SiblingPinObjects                 = 16,
	TARGET_BlueprintLibraries                = 32,
	ContextTargetFlagsEnd                    = 33,
	EContextTargetFlags_MAX                  = 34,
};

// Enum Kismet.EFiBVersion
// NumValues: 0x0007
enum class EFiBVersion : uint64
{
	FIB_VER_NONE                             = 18446744073709551615,
	FIB_VER_BASE                             = 0,
	FIB_VER_VARIABLE_REFERENCE               = 1,
	FIB_VER_INTERFACE_GRAPHS                 = 2,
	FIB_VER_PLUS_ONE                         = 3,
	FIB_VER_LATEST                           = 2,
	FIB_VER_MAX                              = 4,
};

// ScriptStruct Kismet.BlueprintActionMenuItem
// 0x00A8 (0x01A8 - 0x0100)
struct FBlueprintActionMenuItem final : public FEdGraphSchemaAction
{
public:
	uint8                                         Pad_100[0xA8];                                     // 0x0100(0x00A8)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FBlueprintActionMenuItem;

// ScriptStruct Kismet.BlueprintCompiledData
// 0x0010 (0x0010 - 0x0000)
struct FBlueprintCompiledData final
{
public:
	TArray<class UEdGraph*>                       IntermediateGraphs;                                // 0x0000(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FBlueprintCompiledData;

// ScriptStruct Kismet.BlueprintDragDropMenuItem
// 0x0050 (0x0150 - 0x0100)
struct FBlueprintDragDropMenuItem final : public FEdGraphSchemaAction
{
public:
	uint8                                         Pad_100[0x50];                                     // 0x0100(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FBlueprintDragDropMenuItem;

// ScriptStruct Kismet.FavoritedBlueprintPaletteItem
// 0x0070 (0x0070 - 0x0000)
struct alignas(0x08) FFavoritedBlueprintPaletteItem final
{
public:
	uint8                                         Pad_0[0x70];                                       // 0x0000(0x0070)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FFavoritedBlueprintPaletteItem;

// ScriptStruct Kismet.BPGraphClipboardData
// 0x0028 (0x0028 - 0x0000)
struct FBPGraphClipboardData final
{
public:
	class FName                                   GraphName;                                         // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EGraphType                                    GraphType;                                         // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TWeakObjectPtr<class UBlueprint>              OriginalBlueprint;                                 // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class FString                                 NodesString;                                       // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FBPGraphClipboardData;

SDK_NAMESPACE_END
