#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Landscape_Manage_Mode

#include "Basic.hpp"

#include "IntroTutorials_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Landscape_Manage_Mode.Landscape_Manage_Mode_C
// 0x0000 (0x0160 - 0x0160)
class ULandscape_Manage_Mode_C final : public UEditorTutorial
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Landscape_Manage_Mode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Landscape_Manage_Mode_C")
	}
	static class ULandscape_Manage_Mode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULandscape_Manage_Mode_C>();
	}
};
DUMPER7_ASSERTS_ULandscape_Manage_Mode_C;

// BlueprintGeneratedClass Landscape_Manage_Mode.SKEL_Landscape_Manage_Mode_C
// 0x0010 (0x0170 - 0x0160)
class USKEL_Landscape_Manage_Mode_C final : public UEditorTutorial
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0160(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_Landscape_Manage_Mode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_Landscape_Manage_Mode_C")
	}
	static class USKEL_Landscape_Manage_Mode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_Landscape_Manage_Mode_C>();
	}
};
DUMPER7_ASSERTS_USKEL_Landscape_Manage_Mode_C;

SDK_NAMESPACE_END
