#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LandmassEditor

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class LandmassEditor.LandmassActor
// 0x0010 (0x0308 - 0x02F8)
class ALandmassActor: public AActor
{
public:
	bool                                          EditorTickIsEnabled;                               // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2F9[0xF];                                      // 0x02F9(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ActorSelectionChanged(bool bSelected);
	void CustomTick(float DeltaSeconds);
	void SetEditorTickEnabled(bool bEnabled);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LandmassActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LandmassActor")
	}
	static class ALandmassActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALandmassActor>();
	}
};
DUMPER7_ASSERTS_ALandmassActor;

// Class LandmassEditor.LandmassBlueprintFunctionLibrary
// 0x0000 (0x0030 - 0x0030)
class ULandmassBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool GetCursorWorldRay(struct FVector* CameraLocation, struct FVector* RayOrigin, struct FVector* RayDirection);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("LandmassBlueprintFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LandmassBlueprintFunctionLibrary")
	}
	static class ULandmassBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULandmassBlueprintFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_ULandmassBlueprintFunctionLibrary;

SDK_NAMESPACE_END
