#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MessagingRpc

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct MessagingRpc.MessageRpcUnhandled
// 0x0010 (0x0010 - 0x0000)
struct FMessageRpcUnhandled final
{
public:
	struct FGuid                                  CallId;                                            // 0x0000(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMessageRpcUnhandled;

// ScriptStruct MessagingRpc.MessageRpcProgress
// 0x0028 (0x0028 - 0x0000)
struct FMessageRpcProgress final
{
public:
	float                                         Completion;                                        // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGuid                                  CallId;                                            // 0x0004(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 StatusText;                                        // 0x0018(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMessageRpcProgress;

// ScriptStruct MessagingRpc.MessageRpcCancel
// 0x0010 (0x0010 - 0x0000)
struct FMessageRpcCancel final
{
public:
	struct FGuid                                  CallId;                                            // 0x0000(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FMessageRpcCancel;

// ScriptStruct MessagingRpc.RpcMessage
// 0x0010 (0x0010 - 0x0000)
struct FRpcMessage final
{
public:
	struct FGuid                                  CallId;                                            // 0x0000(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FRpcMessage;

SDK_NAMESPACE_END
