#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PortalServices

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum PortalServices.EEntitlementCacheLevelRetrieved
// NumValues: 0x0004
enum class EEntitlementCacheLevelRetrieved : uint8
{
	None                                     = 0,
	Memory                                   = 1,
	Disk                                     = 2,
	EEntitlementCacheLevelRetrieved_MAX      = 3,
};

// Enum PortalServices.EEntitlementCacheLevelRequest
// NumValues: 0x0003
enum class EEntitlementCacheLevelRequest : uint8
{
	Memory                                   = 1,
	Disk                                     = 2,
	EEntitlementCacheLevelRequest_MAX        = 3,
};

// ScriptStruct PortalServices.PortalUserIsEntitledToItemResult
// 0x0018 (0x0018 - 0x0000)
struct FPortalUserIsEntitledToItemResult final
{
public:
	class FString                                 ItemId;                                            // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsEntitled;                                        // 0x0010(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEntitlementCacheLevelRetrieved               RetrievedFromCacheLevel;                           // 0x0011(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPortalUserIsEntitledToItemResult;

// ScriptStruct PortalServices.PortalUserDetails
// 0x0050 (0x0050 - 0x0000)
struct FPortalUserDetails final
{
public:
	class FText                                   DisplayName;                                       // 0x0000(0x0018)(Edit, NativeAccessSpecifierPublic)
	class FText                                   Email;                                             // 0x0018(0x0018)(Edit, NativeAccessSpecifierPublic)
	class FText                                   RealName;                                          // 0x0030(0x0018)(Edit, NativeAccessSpecifierPublic)
	bool                                          IsSignedIn;                                        // 0x0048(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPortalUserDetails;

SDK_NAMESPACE_END
