#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SourceControl

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class SourceControl.SourceControlHelpers
// 0x0000 (0x0030 - 0x0030)
class USourceControlHelpers final : public UObject
{
public:
	static bool CheckInFile(const class FString& InFile, const class FString& InDescription, bool bSilent);
	static bool CheckInFiles(const TArray<class FString>& InFiles, const class FString& InDescription, bool bSilent);
	static bool CheckOutFile(const class FString& InFile, bool bSilent);
	static bool CheckOutFiles(const TArray<class FString>& InFiles, bool bSilent);
	static bool CheckOutOrAddFile(const class FString& InFile, bool bSilent);
	static bool CheckOutOrAddFiles(const TArray<class FString>& InFiles, bool bSilent);
	static bool CopyFile(const class FString& InSourceFile, const class FString& InDestFile, bool bSilent);
	static class FString CurrentProvider();
	static bool IsAvailable();
	static bool IsEnabled();
	static class FText LastErrorMsg();
	static bool MarkFileForAdd(const class FString& InFile, bool bSilent);
	static bool MarkFileForDelete(const class FString& InFile, bool bSilent);
	static bool MarkFilesForAdd(const TArray<class FString>& InFiles, bool bSilent);
	static bool MarkFilesForDelete(const TArray<class FString>& InFiles, bool bSilent);
	static struct FSourceControlState QueryFileState(const class FString& InFile, bool bSilent);
	static bool RevertFile(const class FString& InFile, bool bSilent);
	static bool RevertFiles(const TArray<class FString>& InFiles, bool bSilent);
	static bool RevertUnchangedFile(const class FString& InFile, bool bSilent);
	static bool RevertUnchangedFiles(const TArray<class FString>& InFiles, bool bSilent);
	static bool SyncFile(const class FString& InFile, bool bSilent);
	static bool SyncFiles(const TArray<class FString>& InFiles, bool bSilent);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SourceControlHelpers")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SourceControlHelpers")
	}
	static class USourceControlHelpers* GetDefaultObj()
	{
		return GetDefaultObjImpl<USourceControlHelpers>();
	}
};
DUMPER7_ASSERTS_USourceControlHelpers;

SDK_NAMESPACE_END
