#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StaticMeshEditorTutorial

#include "Basic.hpp"

#include "IntroTutorials_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass StaticMeshEditorTutorial.StaticMeshEditorTutorial_C
// 0x0000 (0x0160 - 0x0160)
class UStaticMeshEditorTutorial_C final : public UEditorTutorial
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("StaticMeshEditorTutorial_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StaticMeshEditorTutorial_C")
	}
	static class UStaticMeshEditorTutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStaticMeshEditorTutorial_C>();
	}
};
DUMPER7_ASSERTS_UStaticMeshEditorTutorial_C;

// BlueprintGeneratedClass StaticMeshEditorTutorial.SKEL_StaticMeshEditorTutorial_C
// 0x0010 (0x0170 - 0x0160)
class USKEL_StaticMeshEditorTutorial_C final : public UEditorTutorial
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0160(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_StaticMeshEditorTutorial_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_StaticMeshEditorTutorial_C")
	}
	static class USKEL_StaticMeshEditorTutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_StaticMeshEditorTutorial_C>();
	}
};
DUMPER7_ASSERTS_USKEL_StaticMeshEditorTutorial_C;

SDK_NAMESPACE_END
