#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TutorialTPP_AnimBlueprint

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass TutorialTPP_AnimBlueprint.TutorialTPP_AnimBlueprint_C
// 0x0150 (0x0450 - 0x0300)
class UTutorialTPP_AnimBlueprint_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2F8[0x8];                                      // 0x02F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0310(0x0040)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x0350(0x00F0)()
	float                                         Speed;                                             // 0x0440(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TutorialTPP_AnimBlueprint(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TutorialTPP_AnimBlueprint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TutorialTPP_AnimBlueprint_C")
	}
	static class UTutorialTPP_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTutorialTPP_AnimBlueprint_C>();
	}
};
DUMPER7_ASSERTS_UTutorialTPP_AnimBlueprint_C;

// AnimBlueprintGeneratedClass TutorialTPP_AnimBlueprint.SKEL_TutorialTPP_AnimBlueprint_C
// 0x0020 (0x0320 - 0x0300)
class USKEL_TutorialTPP_AnimBlueprint_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2F8[0x8];                                      // 0x02F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Speed;                                             // 0x0310(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_TutorialTPP_AnimBlueprint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_TutorialTPP_AnimBlueprint_C")
	}
	static class USKEL_TutorialTPP_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_TutorialTPP_AnimBlueprint_C>();
	}
};
DUMPER7_ASSERTS_USKEL_TutorialTPP_AnimBlueprint_C;

SDK_NAMESPACE_END
