#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterBrushCacheContainer

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "WaterBrushCache_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WaterBrushCacheContainer.WaterBrushCacheContainer_C
// 0x0010 (0x0040 - 0x0030)
class UWaterBrushCacheContainer_C final : public UObject
{
public:
	struct FWaterBrushCache                       Cache;                                             // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WaterBrushCacheContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WaterBrushCacheContainer_C")
	}
	static class UWaterBrushCacheContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWaterBrushCacheContainer_C>();
	}
};
DUMPER7_ASSERTS_UWaterBrushCacheContainer_C;

// BlueprintGeneratedClass WaterBrushCacheContainer.SKEL_WaterBrushCacheContainer_C
// 0x0020 (0x0050 - 0x0030)
class USKEL_WaterBrushCacheContainer_C final : public UObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0030(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	struct FWaterBrushCache                       Cache;                                             // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WaterBrushCacheContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WaterBrushCacheContainer_C")
	}
	static class USKEL_WaterBrushCacheContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WaterBrushCacheContainer_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WaterBrushCacheContainer_C;

SDK_NAMESPACE_END
