#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SubInventoryContainer

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_SubInventoryContainer.WBP_SubInventoryContainer_C
// 0x0000 (0x0408 - 0x0408)
class UWBP_SubInventoryContainer_C final : public UInventoryContainerWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_SubInventoryContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_SubInventoryContainer_C")
	}
	static class UWBP_SubInventoryContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SubInventoryContainer_C>();
	}
};
DUMPER7_ASSERTS_UWBP_SubInventoryContainer_C;

// WidgetBlueprintGeneratedClass WBP_SubInventoryContainer.SKEL_WBP_SubInventoryContainer_C
// 0x0010 (0x0418 - 0x0408)
class USKEL_WBP_SubInventoryContainer_C final : public UInventoryContainerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_SubInventoryContainer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_SubInventoryContainer_C")
	}
	static class USKEL_WBP_SubInventoryContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_SubInventoryContainer_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_SubInventoryContainer_C;

SDK_NAMESPACE_END
