#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Interaction

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_Interaction.WBP_Interaction_C
// 0x0018 (0x0438 - 0x0420)
class UWBP_Interaction_C final : public UInteractionWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0420(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickVerticalBox*                      OptionsBox;                                        // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Interaction(int32 EntryPoint);
	void AddOptionWidget(class UInteractionOptionWidget* Widget, int32 OptionIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Interaction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Interaction_C")
	}
	static class UWBP_Interaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Interaction_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Interaction_C;

// WidgetBlueprintGeneratedClass WBP_Interaction.SKEL_WBP_Interaction_C
// 0x0018 (0x0438 - 0x0420)
class USKEL_WBP_Interaction_C final : public UInteractionWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0420(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickVerticalBox*                      OptionsBox;                                        // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AddOptionWidget(class UInteractionOptionWidget* Widget, int32 OptionIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_Interaction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_Interaction_C")
	}
	static class USKEL_WBP_Interaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_Interaction_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_Interaction_C;

SDK_NAMESPACE_END
