#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputMappings

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InputMappings.SKEL_WBP_InputMappings_C
// 0x0018 (0x0448 - 0x0430)
class USKEL_WBP_InputMappings_C final : public UInputSettingsPageWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	struct FPopupHandle                           ResetPopupHandle;                                  // 0x0440(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void Construct();
	void OnClickedRevertInput();
	void OnRevertInputPopupClosed(EPopupResult Result);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_InputMappings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_InputMappings_C")
	}
	static class USKEL_WBP_InputMappings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_InputMappings_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_InputMappings_C;

// WidgetBlueprintGeneratedClass WBP_InputMappings.WBP_InputMappings_C
// 0x0018 (0x0448 - 0x0430)
class UWBP_InputMappings_C final : public UInputSettingsPageWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	struct FPopupHandle                           ResetPopupHandle;                                  // 0x0440(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void ExecuteUbergraph_WBP_InputMappings(int32 EntryPoint);
	void OnRevertInputPopupClosed(EPopupResult Result);
	void OnClickedRevertInput();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InputMappings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InputMappings_C")
	}
	static class UWBP_InputMappings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputMappings_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InputMappings_C;

SDK_NAMESPACE_END
