#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VehicleDashboard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_Dashboard_classes.hpp"
#include "BrickRigs_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_VehicleDashboard.WBP_VehicleDashboard_C
// 0x0050 (0x0510 - 0x04C0)
class UWBP_VehicleDashboard_C final : public UWBP_Dashboard_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_VehicleDashboard_C;             // 0x04C0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_DashboardSlider_C*                 SpeedSlider;                                       // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 VerticalSpeedSlider;                               // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 AltitudeSlider;                                    // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 RPMSlider;                                         // 0x04E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 GearSlider;                                        // 0x04F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 FuelSlider;                                        // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 AmmoSlider;                                        // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBrick*                                 RefBrick;                                          // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_VehicleDashboard(int32 EntryPoint);
	void PopulateDashboard();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void AddVehicleInputAction(EVehicleInputAxis InputAxis, class FName ActionName, bool bIsSecondaryAction);
	void AddActionsAndSliders();
	void AddFireActions();
	void AddSeatActions();
	void AddSirenActions();
	void AddVehicleInputActions();
	void AddInvincibleAction(class ABrickPlayerController* PC);
	void AddPinActions(class ABrickPlayerController* self2);
	void AddSliders();
	void AddVehicleInputAxes();
	void AddVehicleInputAxis(EVehicleInputAxis InputAxis, EVehicleInputAxis AltAxis, class FName ActionName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_VehicleDashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_VehicleDashboard_C")
	}
	static class UWBP_VehicleDashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_VehicleDashboard_C>();
	}
};
DUMPER7_ASSERTS_UWBP_VehicleDashboard_C;

// WidgetBlueprintGeneratedClass WBP_VehicleDashboard.SKEL_WBP_VehicleDashboard_C
// 0x0050 (0x0510 - 0x04C0)
class USKEL_WBP_VehicleDashboard_C final : public USKEL_WBP_Dashboard_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_SKEL_WBP_VehicleDashboard_C;        // 0x04C0(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_DashboardSlider_C*                 SpeedSlider;                                       // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 VerticalSpeedSlider;                               // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 AltitudeSlider;                                    // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 RPMSlider;                                         // 0x04E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 GearSlider;                                        // 0x04F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 FuelSlider;                                        // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_DashboardSlider_C*                 AmmoSlider;                                        // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBrick*                                 RefBrick;                                          // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void PopulateDashboard();
	void AddVehicleInputAction(EVehicleInputAxis InputAxis, class FName ActionName, bool bIsSecondaryAction);
	void AddActionsAndSliders();
	void AddFireActions();
	void AddSeatActions();
	void AddSirenActions();
	void AddVehicleInputActions();
	void AddInvincibleAction(class ABrickPlayerController* PC);
	void AddPinActions(class ABrickPlayerController* self2);
	void AddSliders();
	void AddVehicleInputAxes();
	void AddVehicleInputAxis(EVehicleInputAxis InputAxis, EVehicleInputAxis AltAxis, class FName ActionName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_VehicleDashboard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_VehicleDashboard_C")
	}
	static class USKEL_WBP_VehicleDashboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_VehicleDashboard_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_VehicleDashboard_C;

SDK_NAMESPACE_END
