#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InventoryCategory

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InventoryCategory.WBP_InventoryCategory_C
// 0x0018 (0x0450 - 0x0438)
class UWBP_InventoryCategory_C final : public UInventoryCategoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0438(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickTextBlock*                        NameTextBlock;                                     // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_InventoryCategory(int32 EntryPoint);
	void InitializeCategory();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InventoryCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InventoryCategory_C")
	}
	static class UWBP_InventoryCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InventoryCategory_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InventoryCategory_C;

// WidgetBlueprintGeneratedClass WBP_InventoryCategory.SKEL_WBP_InventoryCategory_C
// 0x0018 (0x0450 - 0x0438)
class USKEL_WBP_InventoryCategory_C final : public UInventoryCategoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0438(0x0010)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickTextBlock*                        NameTextBlock;                                     // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void InitializeCategory();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_InventoryCategory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_InventoryCategory_C")
	}
	static class USKEL_WBP_InventoryCategory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_InventoryCategory_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_InventoryCategory_C;

SDK_NAMESPACE_END
