#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UserInterfaceSettings

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UserInterfaceSettings.WBP_UserInterfaceSettings_C
// 0x0000 (0x0430 - 0x0430)
class UWBP_UserInterfaceSettings_C final : public UMenuSettingsPageWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UserInterfaceSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UserInterfaceSettings_C")
	}
	static class UWBP_UserInterfaceSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UserInterfaceSettings_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UserInterfaceSettings_C;

// WidgetBlueprintGeneratedClass WBP_UserInterfaceSettings.SKEL_WBP_UserInterfaceSettings_C
// 0x0010 (0x0440 - 0x0430)
class USKEL_WBP_UserInterfaceSettings_C final : public UMenuSettingsPageWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_UserInterfaceSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_UserInterfaceSettings_C")
	}
	static class USKEL_WBP_UserInterfaceSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_UserInterfaceSettings_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_UserInterfaceSettings_C;

SDK_NAMESPACE_END
