#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DeathScreen

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_DeathScreen.WBP_DeathScreen_C
// 0x0000 (0x03F8 - 0x03F8)
class UWBP_DeathScreen_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_DeathScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_DeathScreen_C")
	}
	static class UWBP_DeathScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DeathScreen_C>();
	}
};
DUMPER7_ASSERTS_UWBP_DeathScreen_C;

// WidgetBlueprintGeneratedClass WBP_DeathScreen.SKEL_WBP_DeathScreen_C
// 0x0010 (0x0408 - 0x03F8)
class USKEL_WBP_DeathScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F8(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_DeathScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_DeathScreen_C")
	}
	static class USKEL_WBP_DeathScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_DeathScreen_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_DeathScreen_C;

SDK_NAMESPACE_END
