#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputMappingKey

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InputMappingKey.WBP_InputMappingKey_C
// 0x0010 (0x0468 - 0x0458)
class UWBP_InputMappingKey_C final : public UInputMappingKeyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0458(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_InputMappingKey(int32 EntryPoint);
	void BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);
	void UpdateConflictedState(bool bNewConflicted);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InputMappingKey_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InputMappingKey_C")
	}
	static class UWBP_InputMappingKey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputMappingKey_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InputMappingKey_C;

// WidgetBlueprintGeneratedClass WBP_InputMappingKey.SKEL_WBP_InputMappingKey_C
// 0x0010 (0x0468 - 0x0458)
class USKEL_WBP_InputMappingKey_C final : public UInputMappingKeyWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0458(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void UpdateConflictedState(bool bNewConflicted);
	void BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_InputMappingKey_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_InputMappingKey_C")
	}
	static class USKEL_WBP_InputMappingKey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_InputMappingKey_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_InputMappingKey_C;

SDK_NAMESPACE_END
