#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InteractionIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InteractionIcon.WBP_InteractionIcon_C
// 0x0000 (0x0420 - 0x0420)
class UWBP_InteractionIcon_C final : public UInteractionIconWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InteractionIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InteractionIcon_C")
	}
	static class UWBP_InteractionIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InteractionIcon_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InteractionIcon_C;

// WidgetBlueprintGeneratedClass WBP_InteractionIcon.SKEL_WBP_InteractionIcon_C
// 0x0010 (0x0430 - 0x0420)
class USKEL_WBP_InteractionIcon_C final : public UInteractionIconWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0420(0x0010)(ZeroConstructor, Transient, DuplicateTransient)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SKEL_WBP_InteractionIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SKEL_WBP_InteractionIcon_C")
	}
	static class USKEL_WBP_InteractionIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKEL_WBP_InteractionIcon_C>();
	}
};
DUMPER7_ASSERTS_USKEL_WBP_InteractionIcon_C;

SDK_NAMESPACE_END
